
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5
  publish_frequency: 5
  static_map: true
  resolution: 0.05

obstacle_layer:
  enabled: true
  max_obstacle_height: 2.0
  observation_sources: depth_scan
  depth_scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 1.5